### PR TITLE
Added logging to service script

### PR DESCRIPTION
**Pull request by zeedo**
Each menu run will show stderr and stdout output in /var/log/centaurmenu.log
This will be overwritten at each run.

### CODE REVIEW

**Comment by wormstein** [comment]
Hey, could we set this to something more generic, like dentaurmod.log?

**Comment by wormstein** [comment]
Any way to tell systemd/python to save the logs of the last X runs, instead of overwriting?

**Comment by zeedo** [comment]
I've changed the log file location. To get multiple runs we have to do two things.
1. configure the unit file to append not overwrite.
2. Setup logrotate to rotate them properly so we don't file the disk.
We should definitely do that, but it's a bit more involved with changes to install scripts.

**Comment by zeedo** [comment]
> Hey, could we set this to something more generic, like dentaurmod.log?

Done, set it to modmenuoutput.log To be a bit more descriptive and generic.

**Pull request merged**
