### PR TITLE
Bring the liveboard alive.

### PR DESCRIPTION
**Pull request by wormstein**
Integrated with live movements in centaur software. For this to work you need the recompiled stockfish which print fen.log. I don't want to put stockfish compiled inside the repo so it doesn't overwhelm clonning it. 
Should be very easy to compile the one in my repos.

For lichess and others you just have to add in app.py a way to grab the FEN from the other game software. I saw you use python-chess in lichess. Just throw that in the same fen.log file in centaur... That would be my way to do it.
I just don't want to mess the code in lichess as I don't have a way to test it...

If I try to refresh just the div element but the calls to app.py stops, so no fen is returned and board dissapears. Solution was to simply refresh the entire page.

I reduced epaper display refresh to match the page refresh.

### CODE REVIEW

**Comment by EdNekebno** [comment]
I guess I need to compile stockfish then. :)

Will merge when I can test.

I like the idea of the sockets over constant refreshing btw. I think in the meantime it might be possible to ajax the fen in and use javascript to set up the board. (btw - if the window reloads every two seconds and the image refreshes every two seconds, the image will never have time to refresh - it must refresh from the reload only I think?)

And yup - lichess.py and epaper.py both use python-chess . I integrate those in.

I should say - a little bit in my head is that long term if we can write things to play lichess, emulate eboards, etc, then we end up with a codebase where it isn't so difficult to reproduce what the centaur app does (the adaptive play isn't as difficult an algorithm as they make it sound). Then we remove any issue of proprietary software and it can also update directly. That's a bit longer term though.

**Comment by wormstein** [comment]
Right, there is no need to refresh the image alone, it will with the page... makes sense.
Compiled SF is [here](https://github.com/wormstein/DGTCentaur/tree/stockfish/DGTCentaurMods/engines)

**Comment by EdNekebno** [comment]
I pushed a quick change to make it ajax. It works well. The opponent's pieces show as moved before they're physically moved - but that's a minor issue at the moment.

**Comment by EdNekebno** [comment]
I pushed the code to make the eboard emulation move the pieces on the web and it work. When I get a chance I'll update the epaper in there too so the screen displays.

**Comment by wormstein** [comment]
I think the fact that fen.log don't get deleted after a game it will break things when starting lichess... I will modify stockfish to create the fen.log and stockfish.pipe in /tmp so it gets deleted whnen the board is restarted.

**Pull request merged**
