### PR TITLE
Update switch tool. Simplify by using symlink.

### PR DESCRIPTION
**Pull request by wormstein**
You need to do a deb install first to have the services setup.

The tool will auto-detect is the current repo is installed. Just run `./switch-eny.sh` and confirm.

### CODE REVIEW

**Comment by marcb1309** [comment]
This seems much leaner. 
Somehow we should also add all the missing files from the debian installed version. Like the engines.uci and missing engines folders like books, weights, personalities etc ...
So that all the possibilities can be tested.

**Comment by wormstein** [comment]
Yeah makes sense to add those too. Will add engines folder. 

I will update this PR.

**Comment by wormstein** [comment]
Note to self: fix stopping/starting services 🤦🤦

**Comment by wormstein** [comment]
```
pi@dgtcentaur:~/dev/DGTCentaur/tools/dev-tools $ ./switch-env.sh
This repository is not installed.
Do you want to switch? (y/n): y
Installing in /home/pi
Do you want to link engines too? (y/n): y
--> Linking engines folder:
                /home/pi/.DGTCentaurMods/engines --> DGTCentaurMods/engines
Restarting services
--> Restarting DGTCentaurMods.service
--> Restarting centaurmods-web.service
!!! You are using now a repo as a QA tier. Be careful on your git commits. !!!
Do not add unnecessary files in your commit.
Done. Bye.
```
`lrwxrwxrwx 1 pi pi   32 Jan 28 18:54 engines -> /home/pi/.DGTCentaurMods/engines`
```
pi@dgtcentaur:~/dev/DGTCentaur/tools/dev-tools $ ./switch-env.sh
Your repository is currently installed in /home/pi
Do you want to switch? (y/n): y
This repository is live on board in /home/pi.
Deactivating.
-- > Unlinking engines folder...
Restarting services
--> Restarting DGTCentaurMods.service
--> Restarting centaurmods-web.service
Done. Have a nice day!
```

**Pull request merged**
